# Generated by Django 5.1.5 on 2025-02-08 19:04

from django.db import migrations # type: ignore

from django.contrib.postgres.operations import TrigramExtension # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
