# Generated by Django 5.1.6 on 2025-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_body_post_body_comment_post_body_hack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_image',
            field=models.TextField(default='images/pexels-yankrukov_smaller.jpg', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='hack_image',
            field=models.TextField(default='images/pool_noodle.webp', max_length=60),
        ),
    ]
